### ISSUE TITLE
It gets an error when I run the first block of code in Google Colab.

### ISSUE THREAD

**Issue by OfficialIncubo** [InferenceIllusionist/MilkDropLM-Lite#1]
When I tried to run this Colab for the first time, it got an error after importing. Can you please explain what does that mean?

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/llama_cpp/_ctypes_extensions.py](https://localhost:8080/#) in load_shared_library(lib_base_name, base_path)
     66             try:
---> 67                 return ctypes.CDLL(str(lib_path), **cdll_args)  # type: ignore
     68             except Exception as e:

4 frames
OSError: libcudart.so.12: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/llama_cpp/_ctypes_extensions.py](https://localhost:8080/#) in load_shared_library(lib_base_name, base_path)
     67                 return ctypes.CDLL(str(lib_path), **cdll_args)  # type: ignore
     68             except Exception as e:
---> 69                 raise RuntimeError(f"Failed to load shared library '{lib_path}': {e}")
     70 
     71     raise FileNotFoundError(

RuntimeError: Failed to load shared library '/usr/local/lib/python3.10/dist-packages/llama_cpp/lib/libllama.so': libcudart.so.12: cannot open shared object file: No such file or directory
```

**Comment by InferenceIllusionist** [comment]
Hey @OfficialIncubo, thanks for reaching out and giving us a try. Happy to help here, this is a simple fix. 

The error you're seeing around `libllama.so` happens when you are trying to set up the notebook using a CPU-only runtime on Google Colab. 

To fix it just go to the Runtime menu at the top and hit "Change Runtime"

<img width="167" alt="image" src="https://github.com/user-attachments/assets/e49796bb-a167-4788-8edf-731b4fe91bf0" />

From there select the GPU option instead of CPU. If you are on a free colab you should have access to the NVIDIA T4 GPU to try out MilkDrop Lite.

<img width="419" alt="image" src="https://github.com/user-attachments/assets/8459b39a-cfd7-4abf-adc0-1cd4a0731354" />

Once you connect to the new runtime, try running the script again and the packages should install correctly. If you still run into any issues let me know and I can support.

**Comment by OfficialIncubo** [comment]
It worked like a charm!
...and I tried this with some random settings, but it turned very gibberish.

With normal settings, it does a great job.
Here is a sneak peek of this preset that it was generated via MilkDropLM.

![First Generated MilkDropLM Preset Image Preview](https://github.com/user-attachments/assets/1d459a81-e6d4-4721-a900-6127806c95be)

...and I have renamed it as `Se7enSlasher - MilkDropLM Generated Preset #1.milk`.
The prompt was: `The funky reaction of random texture selection with some sick per-vertex patterns`
Thank you for helping me!

**Comment by InferenceIllusionist** [comment]
@OfficialIncubo Glad you were able to get it working and congrats generating on your first MilkDrop preset! Here's to many more! 🙌 

Sincerely appreciate your feedback and sharing your prompt and output. With this early alpha getting good output can be a bit of a numbers game at times, but your valuable insight into the experience is exactly what why we launched the preview to the public early.

Also we are looking into ways to batch process over colab to streamline the creation of presets in bulk and adding additional QoL features to MilkDropLM Lite, so stay tuned!
